---
- name: Update Tomcat binaries
  hosts: all
  become: yes
  become_user: root

  vars:
    tomcat_base_dir: "/usr/local/tomcat"
    temp_download_dir: "/tmp/tomcat_update"

  tasks:
    - name: Ensure temporary download directory exists
      ansible.builtin.file:
        path: "{{ temp_download_dir }}"
        state: directory
        mode: '0755'

    - name: Download the Tomcat binary from a given version
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ temp_download_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        mode: '0644'
        force: no
      register: download_status

    - name: Unpack the Tomcat archive
      ansible.builtin.unarchive:
        src: "{{ temp_download_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ temp_download_dir }}"
        remote_src: yes
        creates: "{{ temp_download_dir }}/apache-tomcat-{{ tomcat_version }}/bin"

    - name: Copy the new bin directory and overwrite
      ansible.builtin.command:
        cmd: "rsync -av {{ temp_download_dir }}/apache-tomcat-{{ tomcat_version }}/bin/ {{ tomcat_base_dir }}/bin/"

    - name: Copy the new lib directory and overwrite
      ansible.builtin.command:
        cmd: "rsync -av {{ temp_download_dir }}/apache-tomcat-{{ tomcat_version }}/lib/ {{ tomcat_base_dir }}/lib/"
